"""
Django settings for teebusiness_core project.

Generated by 'django-admin startproject' using Django 6.0.5.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv
from django.templatetags.static import static
from django.urls import reverse_lazy
from django.utils.translation import gettext_lazy as _

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load environment variables from the project's .env file.
# IMPORTANT: pass an EXPLICIT path. Under a WSGI server (PythonAnywhere, gunicorn,
# mod_wsgi) the process working directory is NOT the project directory, so a bare
# load_dotenv() (which searches from the CWD) finds nothing — SECRET_KEY and every
# other variable go missing and Django refuses to start. BASE_DIR is derived from
# __file__, so this resolves correctly no matter where the process is launched.
load_dotenv(BASE_DIR / '.env')


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('SECRET_KEY', "odsa&9q%#ic#7q6kwumdl2o=v9(wy1f96ij%6vi2&%)vbouc@s")

# SECURITY WARNING: don't run with debug turned on in production!
# (Set DEBUG=True only for local development.)
DEBUG = os.environ.get('DEBUG', 'False') == 'True'

# Refuse to boot a production instance (DEBUG off) without an explicit SECRET_KEY.
if not DEBUG and not os.environ.get('SECRET_KEY'):
    raise ValueError("SECRET_KEY must be set in the environment when DEBUG=False")

ALLOWED_HOSTS = os.environ.get(
    'DJANGO_ALLOWED_HOSTS',
    'localhost,127.0.0.1,testserver'
).split(',')

ALLOWED_HOSTS.extend([
    'teebusiness.pythonanywhere.com',
    '.ngrok-free.dev',
])
# Normalise: strip blanks and drop duplicates while preserving order.
ALLOWED_HOSTS = list(dict.fromkeys(h.strip() for h in ALLOWED_HOSTS if h.strip()))

# Application definition

INSTALLED_APPS = [
    # Django Unfold — modern admin theme (must come BEFORE django.contrib.admin)
    'unfold',
    'unfold.contrib.filters',
    'unfold.contrib.forms',
    'unfold.contrib.import_export',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'import_export',
    'shop',
    'cart',
    'accounts',
    'pages',
    'communication',
]

# ===== DJANGO UNFOLD (admin theme) =====
UNFOLD = {
    "SITE_TITLE": "TEEBUSINESS Admin",
    "SITE_HEADER": "TEEBUSINESS",
    "SITE_SUBHEADER": "Panneau d'administration",
    "SITE_URL": "/",
    "SITE_LOGO": lambda request: static("assets/images/logo.png"),
    "SITE_ICON": lambda request: static("assets/images/logo.png"),
    "SITE_SYMBOL": "storefront",
    "SHOW_HISTORY": True,
    "SHOW_VIEW_ON_SITE": True,
    "BORDER_RADIUS": "9px",
    "DASHBOARD_CALLBACK": "cart.admin.dashboard_callback",
    # Brand palette derived from the TEEBUSINESS logo (crimson).
    "COLORS": {
        "primary": {
            "50": "#fdf2f4", "100": "#fbe3e7", "200": "#f6c2cb", "300": "#ee94a3",
            "400": "#e25c72", "500": "#c5283d", "600": "#a4182b", "700": "#871322",
            "800": "#6f1320", "900": "#5f141f", "950": "#3f0d15",
        },
    },
    "SIDEBAR": {
        "show_search": True,
        "show_all_applications": True,
        "navigation": [
            {"title": _("Tableau de bord"), "separator": False, "items": [
                {"title": _("Vue d'ensemble"), "icon": "dashboard", "link": reverse_lazy("admin:index")},
            ]},
            {"title": _("Boutique"), "separator": True, "items": [
                {"title": _("Commandes"), "icon": "shopping_cart", "link": reverse_lazy("admin:cart_order_changelist")},
                {"title": _("Produits"), "icon": "inventory_2", "link": reverse_lazy("admin:shop_product_changelist")},
                {"title": _("Stock & tailles"), "icon": "layers", "link": reverse_lazy("admin:shop_productsize_changelist")},
                {"title": _("Catégories"), "icon": "category", "link": reverse_lazy("admin:shop_category_changelist")},
                {"title": _("Marques"), "icon": "sell", "link": reverse_lazy("admin:shop_brand_changelist")},
            ]},
            {"title": _("Clients"), "separator": True, "items": [
                {"title": _("Utilisateurs"), "icon": "group", "link": reverse_lazy("admin:accounts_user_changelist")},
                {"title": _("Abonnés newsletter"), "icon": "mail", "link": reverse_lazy("admin:communication_newslettersubscriber_changelist")},
            ]},
            {"title": _("Communication"), "separator": True, "items": [
                {"title": _("Campagnes email"), "icon": "campaign", "link": reverse_lazy("admin:communication_emailcampaign_changelist")},
                {"title": _("Historique emails"), "icon": "history", "link": reverse_lazy("admin:communication_emailhistory_changelist")},
            ]},
            {"title": _("Sécurité"), "separator": True, "items": [
                {"title": _("Codes OTP"), "icon": "pin", "link": reverse_lazy("admin:accounts_otp_changelist")},
                {"title": _("Journaux de connexion"), "icon": "security", "link": reverse_lazy("admin:accounts_loginsecuritylog_changelist")},
                {"title": _("Groupes & rôles"), "icon": "admin_panel_settings", "link": reverse_lazy("admin:auth_group_changelist")},
            ]},
        ],
    },
}

# django-import-export: keep exports lightweight + predictable.
IMPORT_EXPORT_USE_TRANSACTIONS = True
IMPORT_EXPORT_SKIP_ADMIN_LOG = False

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    # WhiteNoise serves static files (incl. Django admin CSS/JS) under STATIC_URL
    # from STATIC_ROOT when DEBUG=False. Must sit right after SecurityMiddleware.
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    # i18n: pick language from session/cookie (no URL change). Must be after
    # SessionMiddleware and before CommonMiddleware.
    'django.middleware.locale.LocaleMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'accounts.middleware.SecurityHeadersMiddleware',
    'accounts.middleware.LoginAttemptMiddleware',
    'accounts.middleware.RateLimitExceptionHandler',
]

ROOT_URLCONF = 'teebusiness_core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'shop.context_processors.currency_processor',
                'shop.context_processors.business_processor',
                'cart.context_processors.cart_processor',
            ],
        },
    },
]

WSGI_APPLICATION = 'teebusiness_core.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# Custom User Model
AUTH_USER_MODEL = 'accounts.User'

# Authentication backends — email-based login first, username fallback for staff.
AUTHENTICATION_BACKENDS = [
    'accounts.backends.EmailBackend',
    'django.contrib.auth.backends.ModelBackend',
]

# Default Auto Field
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
        'OPTIONS': {
            'min_length': 8,
        }
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'fr'  # French by default

# Available languages for the manual switcher (no URL prefixes — language is
# kept in the session/cookie via LocaleMiddleware, so product URLs/slugs never change).
LANGUAGES = [
    ('fr', 'Français'),
    ('en', 'English'),
]
LOCALE_PATHS = [BASE_DIR / 'locale']

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'          # collectstatic target (served by WhiteNoise)
STATICFILES_DIRS = [BASE_DIR / 'static']        # project source assets

# WhiteNoise: compress + far-future cache headers. Non-manifest (no hashed
# filenames) so a missing {% static %} reference 404s that one asset instead of
# raising a 500 on the whole page. Switch to CompressedManifestStaticFilesStorage
# for cache-busting only after confirming every static reference resolves.
STORAGES = {
    'default': {
        'BACKEND': 'django.core.files.storage.FileSystemStorage',
    },
    'staticfiles': {
        'BACKEND': 'whitenoise.storage.CompressedStaticFilesStorage',
    },
}

MEDIA_URL = 'media/'
MEDIA_ROOT = BASE_DIR / 'media'

LOGIN_URL = 'login'
LOGIN_REDIRECT_URL = 'dashboard'
LOGOUT_REDIRECT_URL = 'home'

# ===== EMAIL CONFIGURATION =====
# Shorthand aliases: set EMAIL_BACKEND=console (or smtp, dummy, locmem) in .env
_EMAIL_BACKEND_ALIASES = {
    'console':   'django.core.mail.backends.console.EmailBackend',
    'smtp':      'django.core.mail.backends.smtp.EmailBackend',
    'brevo':     'communication.email_backends.BrevoApiEmailBackend',
    'dummy':     'django.core.mail.backends.dummy.EmailBackend',
    'filebased': 'django.core.mail.backends.filebased.EmailBackend',
    'locmem':    'django.core.mail.backends.locmem.EmailBackend',
}
# The EMAIL_BACKEND env var selects the PROVIDER (console / smtp / brevo).
# Django itself always uses LoggingEmailBackend, which wraps that provider with
# retry + per-email journaling to EmailHistory (and never raises → no 500s).
_backend_key = os.environ.get('EMAIL_BACKEND', 'console')
EMAIL_PROVIDER_BACKEND = _EMAIL_BACKEND_ALIASES.get(_backend_key, _backend_key)
EMAIL_BACKEND = 'communication.email_backends.LoggingEmailBackend'
EMAIL_MAX_RETRIES = int(os.environ.get('EMAIL_MAX_RETRIES', '2'))
EMAIL_HTTP_TIMEOUT = int(os.environ.get('EMAIL_HTTP_TIMEOUT', '20'))

# Brevo (freemium, 300 emails/day) — HTTPS API that works on PythonAnywhere's
# free tier where outbound SMTP is blocked. Set EMAIL_BACKEND=brevo + this key.
BREVO_API_KEY = os.environ.get('BREVO_API_KEY', '')

EMAIL_HOST = os.environ.get('EMAIL_HOST', 'smtp.gmail.com')
EMAIL_PORT = int(os.environ.get('EMAIL_PORT', 587))
EMAIL_USE_TLS = os.environ.get('EMAIL_USE_TLS', 'True') == 'True'
EMAIL_HOST_USER = os.environ.get('EMAIL_HOST_USER', '')
# Gmail App Passwords are frequently copied as "xxxx xxxx xxxx xxxx" (16 chars +
# spaces). Strip spaces so SMTP auth succeeds regardless of how it was pasted.
EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD', '').replace(' ', '')
DEFAULT_FROM_EMAIL = os.environ.get('DEFAULT_FROM_EMAIL', 'noreply@teebusiness.com')
SERVER_EMAIL = os.environ.get('SERVER_EMAIL', DEFAULT_FROM_EMAIL)

# ===== SITE CONFIGURATION =====
SITE_URL = os.environ.get('SITE_URL', 'http://localhost:8000')

# ===== CHECKOUT =====
TAX_RATE_PERCENT = float(os.environ.get('TAX_RATE_PERCENT', '0'))

# Fixed shipping price by delivery zone.
#   conakry        -> 15 000 FG
#   guinea (inland)-> 20 000 FG
#   international  -> 10 USD (converted to GNF at USD_TO_GNF for the order total)
USD_TO_GNF = int(os.environ.get('USD_TO_GNF', '9100'))  # 1 USD ≈ 9 100 GNF
SHIPPING_DEFAULT_ZONE = 'conakry'
SHIPPING_ZONES = {
    'conakry':       {'label': 'Conakry',                'gnf': int(os.environ.get('SHIP_CONAKRY_GNF', '15000'))},
    'guinea':        {'label': 'Intérieur de la Guinée', 'gnf': int(os.environ.get('SHIP_GUINEA_GNF', '20000'))},
    'international': {'label': 'International',           'usd': int(os.environ.get('SHIP_INTL_USD', '10'))},
}
# Back-compat: some older code referenced a single flat fee.
SHIPPING_COST_GNF = SHIPPING_ZONES['conakry']['gnf']

# Master switch for automatic subscriber product alerts (new/restock/discount).
# Set False (e.g. during data imports/seeding) to avoid emailing on bulk changes.
PRODUCT_NOTIFICATIONS_ENABLED = os.environ.get('PRODUCT_NOTIFICATIONS_ENABLED', 'True') == 'True'

# ===== SMS CONFIGURATION (Twilio — disabled by default) =====
SMS_ENABLED = os.environ.get('SMS_ENABLED', 'False') == 'True'
TWILIO_ACCOUNT_SID = os.environ.get('TWILIO_ACCOUNT_SID', '')
TWILIO_AUTH_TOKEN = os.environ.get('TWILIO_AUTH_TOKEN', '')
TWILIO_PHONE_NUMBER = os.environ.get('TWILIO_PHONE_NUMBER', '')

# Contact Information Constants
BUSINESS_PHONE = os.environ.get('BUSINESS_PHONE', '+224 623 70 78 33')
BUSINESS_EMAIL = os.environ.get('BUSINESS_EMAIL', 'supportteebusiness@gmail.com')
BUSINESS_NAME = os.environ.get('BUSINESS_NAME', 'TEEBUSINESS')

# ===== SOCIAL MEDIA & WHATSAPP =====
SOCIAL_TIKTOK = os.environ.get('SOCIAL_TIKTOK', 'https://www.tiktok.com/@teebusines')
SOCIAL_FACEBOOK = os.environ.get(
    'SOCIAL_FACEBOOK', 'https://www.facebook.com/share/17Yxep5woR/?mibextid=wwXIfr'
)
# WhatsApp support number (digits only, no +/spaces) derived from BUSINESS_PHONE.
WHATSAPP_NUMBER = os.environ.get(
    'WHATSAPP_NUMBER', ''.join(ch for ch in BUSINESS_PHONE if ch.isdigit())
)
WHATSAPP_MESSAGE = os.environ.get(
    'WHATSAPP_MESSAGE', 'Hello, I would like information about your products.'
)

# ===== SECURITY SETTINGS =====
CSRF_COOKIE_SECURE = not DEBUG
SESSION_COOKIE_SECURE = not DEBUG
SESSION_COOKIE_HTTPONLY = True
CSRF_COOKIE_HTTPONLY = True
SESSION_COOKIE_AGE = 30 * 24 * 60 * 60  # 30 days
SESSION_COOKIE_SAMESITE = 'Lax'
CSRF_COOKIE_SAMESITE = 'Lax'

X_FRAME_OPTIONS = 'DENY'
SECURE_BROWSER_XSS_FILTER = True
SECURE_CONTENT_TYPE_NOSNIFF = True
SECURE_SSL_REDIRECT = os.environ.get('SECURE_SSL_REDIRECT', 'False') == 'True'

# ===== PROXY / CLOUDFLARE COMPATIBILITY =====
# Cloudflare (and most reverse proxies) terminate TLS and forward the original
# scheme in X-Forwarded-Proto. This lets request.is_secure() report correctly so
# secure cookies and HTTPS-only behaviour work behind the proxy.
# Safe to enable only when the app always sits behind a trusted proxy in prod.
if os.environ.get('USE_PROXY_SSL_HEADER', 'False') == 'True':
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

# Domains allowed to submit cross-origin POST/CSRF (your production hostnames).
# e.g. CSRF_TRUSTED_ORIGINS=https://teebusiness.com,https://www.teebusiness.com
CSRF_TRUSTED_ORIGINS = [
    o.strip().rstrip('/') for o in os.environ.get('CSRF_TRUSTED_ORIGINS', '').split(',') if o.strip()
]
# Safety net: every non-local allowed host is also a trusted HTTPS CSRF origin,
# so admin/login POST works on the production domain even if the env var is unset.
for _host in ALLOWED_HOSTS:
    _h = _host.strip().rstrip('/')
    if _h and not _h.startswith('.') and _h not in ('localhost', '127.0.0.1', 'testserver'):
        _origin = f"https://{_h.split('//')[-1]}"
        if _origin not in CSRF_TRUSTED_ORIGINS:
            CSRF_TRUSTED_ORIGINS.append(_origin)

# HSTS Settings (only in production)
if not DEBUG:
    SECURE_HSTS_SECONDS = int(os.environ.get('SECURE_HSTS_SECONDS', 31536000))
    SECURE_HSTS_INCLUDE_SUBDOMAINS = os.environ.get('SECURE_HSTS_INCLUDE_SUBDOMAINS', 'True') == 'True'
    SECURE_HSTS_PRELOAD = os.environ.get('SECURE_HSTS_PRELOAD', 'True') == 'True'

# Content-Security-Policy. NOTE: Django 5.2 has no native CSP setting
# (SECURE_CSP arrives in 6.0), so this is emitted by SecurityHeadersMiddleware.
# 'unsafe-inline' is required because the UI uses inline scripts/styles
# (Alpine, Tailwind CDN, chart init). 'unsafe-eval' is required because
# Alpine.js' default build evaluates directive expressions via new Function();
# without it every Alpine component (popups, dropdowns, this widget) is inert.
# It still restricts external origins.
CONTENT_SECURITY_POLICY = (
    "default-src 'self'; "
    "script-src 'self' 'unsafe-inline' 'unsafe-eval' https://cdn.jsdelivr.net https://cdn.tailwindcss.com; "
    "style-src 'self' 'unsafe-inline' https://fonts.googleapis.com https://cdn.tailwindcss.com; "
    "font-src 'self' https://fonts.gstatic.com data:; "
    "img-src 'self' data: blob: https:; "
    "connect-src 'self'; "
    "frame-ancestors 'none'; "
    "base-uri 'self'; "
    "form-action 'self'"
)

# ===== PASSWORD RESET SETTINGS =====
PASSWORD_RESET_TIMEOUT = 3600 * 24  # 24 hours
PASSWORD_RESET_CONFIRM_TIMEOUT = 3600  # 1 hour in URL (actual token in session)

# ===== RATE LIMITING SETTINGS =====
RATELIMIT_ENABLE = os.environ.get('RATELIMIT_ENABLE', 'True') == 'True'
MAX_LOGIN_ATTEMPTS = int(os.environ.get('MAX_LOGIN_ATTEMPTS', 5))
LOCKOUT_DURATION = int(os.environ.get('LOCKOUT_DURATION', 900))  # 15 minutes
REQUIRE_EMAIL_VERIFICATION_ATTEMPTS = int(os.environ.get('REQUIRE_EMAIL_VERIFICATION_ATTEMPTS', 10))

# ===== OTP SETTINGS =====
OTP_EXPIRATION_MINUTES = int(os.environ.get('OTP_EXPIRATION_MINUTES', 10))
OTP_RESEND_LIMIT = int(os.environ.get('OTP_RESEND_LIMIT', 5))
OTP_RESEND_COOLDOWN_MINUTES = int(os.environ.get('OTP_RESEND_COOLDOWN_MINUTES', 2))

# ===== CACHE SETTINGS =====
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
        'LOCATION': 'teebusiness-cache',
    }
}

# ===== LOGGING SETTINGS =====
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
        },
    },
    'root': {
        'handlers': ['console'],
        'level': 'INFO',
    },
    'loggers': {
        'django': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,
        },
        'accounts': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,
        },
    },
}

# File logging only in development (not on PythonAnywhere)
if DEBUG:
    try:
        logs_dir = BASE_DIR / 'logs'
        logs_dir.mkdir(exist_ok=True)
        LOGGING['handlers']['file'] = {
            'level': 'INFO',
            'class': 'logging.FileHandler',
            'formatter': 'verbose',
            'filename': logs_dir / 'django.log',
        }
        LOGGING['loggers']['accounts']['handlers'] = ['file', 'console']
    except Exception:
        # Silently fail if we can't create logs directory
        pass
