# Generated by Django 5.2.12 on 2026-06-10 23:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_alter_newslettersubscriber_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NewsletterSubscriber',
        ),
    ]
