# Generated by Django 5.2.12 on 2026-06-10 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loginsecuritylog',
            name='event_type',
            field=models.CharField(choices=[('login_success', 'Login Success'), ('login_failed', 'Login Failed'), ('logout', 'Logout'), ('account_locked', 'Account Locked'), ('account_unlocked', 'Account Unlocked'), ('password_changed', 'Password Changed'), ('otp_verified', 'OTP Verified'), ('otp_failed', 'OTP Failed'), ('suspicious_activity', 'Suspicious Activity')], max_length=30),
        ),
    ]
