# Generated by Django 5.2.12 on 2026-06-20 01:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_address_user_city_user_country'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OTP',
        ),
    ]
