# Generated by Django 5.2.12 on 2026-06-06 08:22

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailCampaign',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('campaign_type', models.CharField(choices=[('promotional', 'Promotional'), ('restock', 'Restock Alert'), ('new_arrival', 'New Arrival'), ('discount', 'Discount Campaign'), ('announcement', 'Announcement'), ('newsletter', 'Newsletter')], max_length=20)),
                ('subject', models.CharField(max_length=255)),
                ('preview_text', models.CharField(blank=True, help_text='Text shown in email preview', max_length=255)),
                ('html_content', models.TextField()),
                ('plain_text_content', models.TextField(blank=True)),
                ('from_email', models.EmailField(default='supportteebusiness@gmail.com', max_length=254)),
                ('reply_to', models.EmailField(blank=True, max_length=254, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('scheduled', 'Scheduled'), ('sending', 'Sending'), ('sent', 'Sent'), ('paused', 'Paused'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('total_recipients', models.PositiveIntegerField(default=0)),
                ('sent_count', models.PositiveIntegerField(default=0)),
                ('delivered_count', models.PositiveIntegerField(default=0)),
                ('opened_count', models.PositiveIntegerField(default=0)),
                ('clicked_count', models.PositiveIntegerField(default=0)),
                ('failed_count', models.PositiveIntegerField(default=0)),
                ('scheduled_for', models.DateTimeField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_campaigns', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Email Campaign',
                'verbose_name_plural': 'Email Campaigns',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CampaignRecipient',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('delivered', 'Delivered'), ('opened', 'Opened'), ('clicked', 'Clicked'), ('failed', 'Failed'), ('bounced', 'Bounced')], default='pending', max_length=20)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('opened_at', models.DateTimeField(blank=True, null=True)),
                ('clicked_at', models.DateTimeField(blank=True, null=True)),
                ('failed_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('tracking_id', models.CharField(blank=True, max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='communication.emailcampaign')),
            ],
            options={
                'verbose_name': 'Campaign Recipient',
                'verbose_name_plural': 'Campaign Recipients',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NewsletterSubscriber',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('subscription_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('unsubscribed', 'Unsubscribed'), ('pending', 'Pending Verification'), ('bounced', 'Bounced')], default='pending', max_length=20)),
                ('source', models.CharField(choices=[('website', 'Website'), ('checkout', 'Checkout'), ('admin', 'Admin'), ('import', 'Import'), ('social', 'Social Media')], default='website', max_length=20)),
                ('verification_token', models.CharField(blank=True, max_length=100, null=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('unsubscribed_at', models.DateTimeField(blank=True, null=True)),
                ('unsubscribe_reason', models.TextField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Newsletter Subscriber',
                'verbose_name_plural': 'Newsletter Subscribers',
                'ordering': ['-subscription_date'],
                'indexes': [models.Index(fields=['email'], name='communicati_email_4037c4_idx'), models.Index(fields=['status'], name='communicati_status_7320a4_idx'), models.Index(fields=['subscription_date'], name='communicati_subscri_667697_idx')],
            },
        ),
        migrations.AddField(
            model_name='emailcampaign',
            name='target_subscribers',
            field=models.ManyToManyField(related_name='campaigns', through='communication.CampaignRecipient', to='communication.newslettersubscriber'),
        ),
        migrations.AddField(
            model_name='campaignrecipient',
            name='subscriber',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='communication.newslettersubscriber'),
        ),
        migrations.CreateModel(
            name='EmailHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email_type', models.CharField(choices=[('otp', 'OTP Verification'), ('welcome', 'Welcome Email'), ('password_reset', 'Password Reset'), ('campaign', 'Campaign Email'), ('notification', 'Notification'), ('transactional', 'Transactional')], max_length=20)),
                ('to_email', models.EmailField(max_length=254)),
                ('from_email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('delivered', 'Delivered'), ('failed', 'Failed'), ('bounced', 'Bounced')], default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('campaign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='email_history', to='communication.emailcampaign')),
                ('related_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_emails', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Email History',
                'verbose_name_plural': 'Email History',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['to_email'], name='communicati_to_emai_36dedd_idx'), models.Index(fields=['email_type'], name='communicati_email_t_efd77c_idx'), models.Index(fields=['status'], name='communicati_status_164b3b_idx'), models.Index(fields=['created_at'], name='communicati_created_7f0e6f_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='emailcampaign',
            index=models.Index(fields=['status'], name='communicati_status_00d2a9_idx'),
        ),
        migrations.AddIndex(
            model_name='emailcampaign',
            index=models.Index(fields=['campaign_type'], name='communicati_campaig_8b39de_idx'),
        ),
        migrations.AddIndex(
            model_name='emailcampaign',
            index=models.Index(fields=['scheduled_for'], name='communicati_schedul_e15985_idx'),
        ),
        migrations.AddIndex(
            model_name='campaignrecipient',
            index=models.Index(fields=['status'], name='communicati_status_29a5d5_idx'),
        ),
        migrations.AddIndex(
            model_name='campaignrecipient',
            index=models.Index(fields=['tracking_id'], name='communicati_trackin_8aa594_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='campaignrecipient',
            unique_together={('campaign', 'subscriber')},
        ),
    ]
