# Generated by Django 5.2.12 on 2026-06-10 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailcampaign',
            name='from_email',
            field=models.EmailField(default='your-email@gmail.com', max_length=254),
        ),
    ]
