# Generated by Django 5.2.12 on 2026-06-11 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0002_alter_emailcampaign_from_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newslettersubscriber',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='newslettersubscriber',
            name='full_name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
