# Generated by Django 5.2.12 on 2026-06-13 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0003_alter_newslettersubscriber_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailcampaign',
            name='from_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
