# Generated by Django 5.2.12 on 2026-06-20 01:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0004_alter_emailcampaign_from_email'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EmailHistory',
        ),
    ]
