# Generated by Django 5.2.12 on 2026-06-19 23:13

from django.db import migrations, models


def dedupe_product_sizes(apps, schema_editor):
    """Collapse any duplicate (product, size) rows before the unique constraint.
    Keep the row with the highest quantity; delete the rest."""
    ProductSize = apps.get_model('shop', 'ProductSize')
    from django.db.models import Count
    dup_groups = (ProductSize.objects.values('product_id', 'size')
                  .annotate(n=Count('id')).filter(n__gt=1))
    for g in dup_groups:
        rows = list(ProductSize.objects.filter(product_id=g['product_id'], size=g['size'])
                    .order_by('-quantity', 'id'))
        for extra in rows[1:]:
            extra.delete()


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_alter_productimage_image'),
    ]

    operations = [
        migrations.RunPython(dedupe_product_sizes, noop),
        migrations.AddConstraint(
            model_name='productsize',
            constraint=models.UniqueConstraint(fields=('product', 'size'), name='uniq_product_size'),
        ),
    ]
