# Generated by Django 5.2.12 on 2026-06-18 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='shipping_zone',
            field=models.CharField(blank=True, default='conakry', max_length=20),
        ),
    ]
